name: ds-job-bot

on:
  schedule:
    - cron: "*/1 * * * *"   # every 30 minutes (UTC)
  workflow_dispatch:         # allow manual run

permissions:
  contents: read

concurrency:
  group: ds-job-bot
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      - name: Run bot
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL:   ${{ secrets.SLACK_CHANNEL }}
          ADZUNA_APP_ID:   ${{ secrets.ADZUNA_APP_ID }}
          ADZUNA_APP_KEY:  ${{ secrets.ADZUNA_APP_KEY }}
          ADZUNA_COUNTRY:  us
          USAJOBS_API_KEY: ${{ secrets.USAJOBS_API_KEY }}
          USAJOBS_EMAIL:   ${{ secrets.USAJOBS_EMAIL }}
          RECENCY_DAYS:    ${{ vars.RECENCY_DAYS }}
          MAX_ITEMS_PER_RUN: ${{ vars.MAX_ITEMS_PER_RUN }}
          ALLOW_INTERNSHIPS: ${{ vars.ALLOW_INTERNSHIPS }}
          SNAPSHOT_N:      ${{ vars.SNAPSHOT_N }}
        run: |
          . .venv/bin/activate
          python main.py

      - name: Upload run artifacts (CSV / preview)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/
          retention-days: 7
